language: node_js
node_js:
- '6'
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli bower
- chmod +x ./travis/build.sh
cache:
  directories:
  - node_modules
  - bower_components
script: "./travis/build.sh"
notifications:
  slack:
    secure: hn8KZIEI2y3r88QGLOnt+KKfpL2yHlF7rVtmZUqMHq2qFw8R0+AoAZ6Ie5xt51DIxQ8AJXjp0AQTA7kPv53Yhmwg7624XNrAfQnymMzVvwisz0F61K6r27ESB6bmSwo+HdjPUi+cyDwE0pZAxVtqAbjPI/vXCmYXiPaqyUJ0Niq8e+iMjzmWkscfkYKmMWZDt3t+5CNQiK4b7+j61zDKRZ+sXyspVA2suw8cxJ8f6bmnR2ipBddqlcqr8aETd3uocvFGUmm+Xh4sg+B/rIJ8zRZesp1i8rYpriMBTAXXBpjmnfRNY6UaoZK3zgbbvz3RafecMxijx5nbS0Hv2H0fGy0EbKgBjbkZM4j3zWyubuLIZagNe3n2AIhC4hBkkvz0kJseTcUJB5Dp2JPlWcqshBNYH/mDr4inDLKPR+qEI/KltSqXB3CAlciAi6BsCFzxEGIyqQzFh9X4jmI3eaMMlZIQoFsp7sedObYS9+PBhKxUroIJEvV3HkDi+pYZJjgUc2sqNE8ensfpyl7ztRA394gomDQa5Qks/pnY7+Nz+b3BKLhTxydOGIRRqhkUvZywAv4LSRWEZVheU7Sxz+53WGl/SXLYMzg6mL7RzzeOywcj4PKrQUlwABtfOzjlMPiEyfbOVcqy0RS30K3/K+oGNHK5I4H94h/ZFcWDsSSmLGU=
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: k9ZbHRNLeJ5UltjncVZVe0aE5yiMNME83CCQyYbQf3l5LRxjBfcw2fHpvIoIDM/3hZduU/g9kQwR9nSfwmsFnqFo3MQQaO33SkAymMmDDzFlJ5C/PTJgUeaPKKPwM7hVCuWry87419Ufh8gp+LhSbKy56olP/NiumXerXPnQ2rw=
  app:
    develop: ncarb-styleguide
    travis: ncarb-styleguide-travis
